### ISSUE TITLE
Wrong capitalization in examples/Recieve

### ISSUE THREAD

**Issue by ulrichmuc** [oshawa-connection/rc-switch-pico#2]
The CMakeLists.txt-file says recieve.cc, but the source-file is Recieve.cc.
Same inconsistency in examples/Transmit

This leads to two error messages when running cmake.

**Comment by oshawa-connection** [comment]
Hi Ulrich, thanks very much for these issues. Could you make a pull request for these changes and I'll accept them, I'm away from home without access to a Pico! If not I will do them in a week or two.
Danke schön

**Comment by oshawa-connection** [comment]
Hi @ulrichmuc, just pushed those changes, give it a go and let me know if there are any more issues 😎
