### ISSUE TITLE
Inconsistent spelling receive / recieve

### ISSUE THREAD

**Issue by ulrichmuc** [oshawa-connection/rc-switch-pico#3]
The member functions of RCSwitch are correctly spelled getReceived*(),
but the directory in examples is called Recieve and the source file is called recieve.cc
and uses "IE" or "ie" in messages and constants declared.
This is rather confusing, especially for a not-native speaker of English like me.

**Comment by oshawa-connection** [comment]
I've just fixed this! Thanks for raising the issue 🙂
